package providers

import (
	"database/sql"
	"fmt"
	"html"
	"html/template"
	"io/fs"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"codeberg.org/urutau-ltd/gavia/internal/models/provider"
	"codeberg.org/urutau-ltd/gavia/internal/ui"
)

// defaultLimit and maxLimit keep list endpoints bounded even when query params are missing or invalid.
const (
	defaultLimit int = 10
	maxLimit     int = 100
)

// Handler coordinates HTTP endpoints, HTML templates and repository calls for the providers feature.
// It lives in the UI layer to keep transport concerns separate from SQL code.
type Handler struct {
	logger       *slog.Logger
	tmpl         *template.Template
	providerRepo *provider.ProviderRepository
}

// pageData is the template contract for providers screens.
// Keeping view state in one struct makes it explicit which fields drive the list/editor partials.
type pageData struct {
	// This data is generated by Gavia. If you need to change this in some
	// way, please refer to internal/ui/common.go
	ui.BaseData

	// The array to store queried providers
	Providers []*provider.Provider

	// A single provider to be shown
	Provider *provider.Provider

	// A searchTerm used in the search bar shown in provider-list.html
	SearchTerm string

	// The maximum amount of providers to show on the provider-list.html
	// component.
	Limit      int
	EditorMode string
	FormAction string
	FormSubmit string
	NoticeHTML template.HTML
	ErrorHTML  template.HTML
}

// NewHandler builds the providers feature handler and preloads all templates it needs.
// Parsing once at startup avoids repeated template work on every request.
func NewHandler(l *slog.Logger, uiFS fs.FS, db *sql.DB) *Handler {
	t := template.Must(template.ParseFS(uiFS,
		"layout/base.html",
		"features/providers/views/*.html",
		"components/*.html",
	))

	return &Handler{
		logger:       l,
		tmpl:         t,
		providerRepo: provider.NewProviderRepository(db),
	}
}

// Index serves GET /providers.
// It returns either the full page or only the list fragment, depending on HTMX headers.
func (h *Handler) Index(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	writeHTMLHeader(w)
	if h.isListRequest(r) {
		h.renderTemplate(w, "provider-list", data)
		return
	}

	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// New serves GET /providers/new and prepares the editor in create mode.
// The same endpoint supports full-page rendering and editor-only HTMX swaps.
func (h *Handler) New(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	data.EditorMode = "new"
	data.FormAction = "/providers"
	data.FormSubmit = "Crear provider"
	data.Provider = &provider.Provider{}

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Show serves GET /providers/{id} and loads the detail panel.
// It keeps list state alive so users can inspect rows without losing current filters.
func (h *Handler) Show(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	p, err := h.providerRepo.GetByID(r.Context(), id)
	if err != nil {
		h.logger.Error("Failed to load provider", "id", id, "err", err)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "No se pudo cargar el provider.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if p == nil {
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("warn", "Provider no encontrado.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusNotFound)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	data.EditorMode = "detail"
	data.Provider = p

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Edit serves GET /providers/{id}/edit and pre-fills the form with current values.
// This endpoint is intentionally read-only; persistence happens in Update.
func (h *Handler) Edit(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	p, err := h.providerRepo.GetByID(r.Context(), id)
	if err != nil {
		h.logger.Error("Failed to load provider for edit", "id", id, "err", err)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "No se pudo cargar el provider para editar.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if p == nil {
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("warn", "Provider no encontrado.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusNotFound)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	data.EditorMode = "edit"
	data.Provider = p
	data.FormAction = fmt.Sprintf("/providers/%s/edit", p.Id)
	data.FormSubmit = "Update provider"

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Create handles POST /providers and persists a new provider.
// After successful creation it returns both refreshed editor and list fragments for HTMX.
func (h *Handler) Create(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "invalid form", http.StatusBadRequest)
		return
	}

	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	name := strings.TrimSpace(r.Form.Get("name"))
	website := strings.TrimSpace(r.Form.Get("website"))
	notes := strings.TrimSpace(r.Form.Get("notes"))

	data.EditorMode = "new"
	data.FormAction = "/providers"
	data.FormSubmit = "Crear provider"
	data.Provider = &provider.Provider{
		Name:    name,
		Website: website,
		Notes:   notes,
	}

	if name == "" {
		data.ErrorHTML = bannerHTML("bad", "El nombre es obligatorio.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if err := h.providerRepo.Create(r.Context(), data.Provider); err != nil {
		h.logger.Error("Failed to create provider", "err", err)
		status := http.StatusInternalServerError
		msg := "No se pudo crear el provider."
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			status = http.StatusConflict
			msg = "Ya existe un provider con ese nombre."
		}
		data.ErrorHTML = bannerHTML("bad", msg)
		writeHTMLHeader(w)
		w.WriteHeader(status)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	updatedProviders, listErr := h.providerRepo.GetAll(r.Context(), data.SearchTerm, data.Limit)
	if listErr != nil {
		h.logger.Error("Failed to refresh provider list", "err", listErr)
	} else {
		data.Providers = updatedProviders
	}

	data.EditorMode = "detail"
	data.NoticeHTML = bannerHTML("ok", "Provider creado correctamente.")

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-response", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Update handles POST /providers/{id}/edit and persists provider changes.
// It validates existence first to distinguish not-found from write failures.
func (h *Handler) Update(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "invalid form", http.StatusBadRequest)
		return
	}

	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	name := strings.TrimSpace(r.Form.Get("name"))
	website := strings.TrimSpace(r.Form.Get("website"))
	notes := strings.TrimSpace(r.Form.Get("notes"))

	data.EditorMode = "edit"
	data.FormAction = fmt.Sprintf("/providers/%s/edit", id)
	data.FormSubmit = "Actualizar provider"
	data.Provider = &provider.Provider{
		Id:      id,
		Name:    name,
		Website: website,
		Notes:   notes,
	}

	if name == "" {
		data.ErrorHTML = bannerHTML("bad", "El nombre es obligatorio.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	current, findErr := h.providerRepo.GetByID(r.Context(), id)
	if findErr != nil {
		h.logger.Error("Failed to load provider for update", "id", id, "err", findErr)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "No se pudo validar el provider a actualizar.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if current == nil {
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("warn", "Provider no encontrado.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusNotFound)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if err := h.providerRepo.Update(r.Context(), data.Provider); err != nil {
		h.logger.Error("Failed to update provider", "id", id, "err", err)
		status := http.StatusInternalServerError
		msg := "No se pudo actualizar el provider."
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			status = http.StatusConflict
			msg = "Ya existe un provider con ese nombre."
		}
		data.ErrorHTML = bannerHTML("bad", msg)
		writeHTMLHeader(w)
		w.WriteHeader(status)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	refreshed, getErr := h.providerRepo.GetByID(r.Context(), id)
	if getErr != nil {
		h.logger.Error("Failed to reload provider after update", "id", id, "err", getErr)
	} else if refreshed != nil {
		data.Provider = refreshed
	}

	updatedProviders, listErr := h.providerRepo.GetAll(r.Context(), data.SearchTerm, data.Limit)
	if listErr != nil {
		h.logger.Error("Failed to refresh provider list", "err", listErr)
	} else {
		data.Providers = updatedProviders
	}

	data.EditorMode = "detail"
	data.NoticeHTML = bannerHTML("ok", "Provider actualizado correctamente.")

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-response", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Delete handles DELETE /providers/{id}.
// On success it refreshes the list and resets the editor state so UI stays coherent.
func (h *Handler) Delete(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "invalid form", http.StatusBadRequest)
		return
	}

	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list providers", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	if err := h.providerRepo.Delete(r.Context(), id); err != nil {
		h.logger.Error("Failed to delete provider", "id", id, "err", err)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "Unable to delete provider.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "provider-editor-response", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	updatedProviders, listErr := h.providerRepo.GetAll(r.Context(), data.SearchTerm, data.Limit)
	if listErr != nil {
		h.logger.Error("Failed to refresh provider list", "err", listErr)
	} else {
		data.Providers = updatedProviders
	}

	data.EditorMode = "flash"
	data.NoticeHTML = bannerHTML("ok", "Provider deleted successfully.")

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "provider-editor-response", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// loadPageData gathers list state and records needed by provider templates.
// Centralizing this avoids duplicating filter+query wiring across handlers.
func (h *Handler) loadPageData(r *http.Request, start time.Time) (pageData, error) {
	searchTerm, limit := parseListState(r)
	providers, err := h.providerRepo.GetAll(r.Context(), searchTerm, limit)
	if err != nil {
		return pageData{}, err
	}

	return pageData{
		BaseData:   ui.NewBaseData("Providers", start),
		Providers:  providers,
		SearchTerm: searchTerm,
		Limit:      limit,
		EditorMode: "empty",
		FormAction: "/providers",
		FormSubmit: "Create provider",
	}, nil
}

// renderTemplate executes a named template and logs rendering failures.
// Keeping this helper avoids repeating identical error handling in each endpoint.
func (h *Handler) renderTemplate(w http.ResponseWriter, tmpl string, data any) {
	if err := h.tmpl.ExecuteTemplate(w, tmpl, data); err != nil {
		h.logger.Error("Error rendering template", "template", tmpl, "err", err)
	}
}

// isListRequest detects HTMX calls that target only the providers table body.
// This allows one route to serve both full and partial responses safely.
func (h *Handler) isListRequest(r *http.Request) bool {
	if r.Header.Get("HX-Request") != "true" || r.Header.Get("HX-Boosted") == "true" {
		return false
	}

	target := strings.TrimSpace(r.Header.Get("HX-Target"))
	if target == "providers-body" || target == "#providers-body" {
		return true
	}

	trigger := strings.TrimSpace(r.Header.Get("HX-Trigger"))
	triggerName := strings.TrimSpace(r.Header.Get("HX-Trigger-Name"))

	return trigger == "provider-limit" ||
		trigger == "provider-search" ||
		triggerName == "limit" ||
		triggerName == "q"
}

// isEditorRequest detects HTMX calls that target the right-side provider editor panel.
func (h *Handler) isEditorRequest(r *http.Request) bool {
	if r.Header.Get("HX-Request") != "true" || r.Header.Get("HX-Boosted") == "true" {
		return false
	}

	target := strings.TrimSpace(r.Header.Get("HX-Target"))
	return target == "provider-editor" || target == "#provider-editor"
}

// parseListState reads query/form list controls shared by full requests and HTMX swaps.
func parseListState(r *http.Request) (string, int) {
	_ = r.ParseForm()
	searchTerm := strings.TrimSpace(r.Form.Get("q"))
	limit := parseLimit(r.Form.Get("limit"))
	return searchTerm, limit
}

// parseLimit normalizes user-provided limits into a safe range.
func parseLimit(raw string) int {
	if raw == "" {
		return defaultLimit
	}

	limit, err := strconv.Atoi(raw)
	if err != nil || limit <= 0 {
		return defaultLimit
	}

	if limit > maxLimit {
		return maxLimit
	}

	return limit
}

// bannerHTML builds a sanitized alert block compatible with Missing.css semantic classes.
func bannerHTML(kind, msg string) template.HTML {
	className := "info"
	switch kind {
	case "ok", "bad", "warn", "info":
		className = kind
	}

	escaped := html.EscapeString(msg)
	return template.HTML(`<p class="provider-alert ` + className + `">` + escaped + `</p>`)
}

// writeHTMLHeader enforces a consistent HTML content type for template responses.
func writeHTMLHeader(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
}
