INSERT OR REPLACE INTO providers (name, website, notes) VALUES
("Namecheap", "https://www.namecheap.com/", "Popular and affordable registrar"),
("GoDaddy", "https://www.godaddy.com/", "Large company, frequent upselling"),
("Google Domains", "https://domains.google/", "Integration with Google services"),
("Cloudflare Registrar", "https://www.cloudflare.com/registrar/", "Cost-price pricing, no markup"),
("Hover", "https://www.hover.com/", "Simple interface, domain-focused"),
("Dynadot", "https://www.dynadot.com/", "Competitive pricing and marketplace"),
("Gandi", "https://www.gandi.net/", "Focus on privacy and ethics"),
("OVHcloud", "https://www.ovh.com/", "European provider with additional services"),
("1&1 IONOS", "https://www.ionos.com/", "Integrated hosting and domain services"),
("Name.com", "https://www.name.com/", "Good option for domains and SSL"),
("Bluehost", "https://www.bluehost.com/", "Hosting + registration, popular for WordPress"),
("DreamHost", "https://www.dreamhost.com/", "Hosting and domains, clear policies"),
("Register.com", "https://www.register.com/", "Traditional registrar"),
("EuroDNS", "https://www.eurodns.com/", "Strong in European TLDs"),
("MarkMonitor", "https://www.markmonitor.com/", "Brand protection and enterprise-focused"),
("Tucows (OpenSRS)", "https://www.tucows.com/", "Wholesale platform, OpenSRS"),
("Enom", "https://www.enom.com/", "Popular wholesale provider"),
("NameSilo", "https://www.namesilo.com/", "Low prices and cheap renewals"),
("Key-Systems", "https://www.key-systems.net/", "European registrar and backend"),
("NetEarth One", "https://www.netearth1.com/", "Accredited registrar"),
("Porkbun", "https://porkbun.com/", "Competitive pricing and simple interface"),
("EuroRegister", "https://www.euroregister.com/", "Focus on the European market"),
("PSI-USA", "https://www.psi-usa.info/", "Infrastructure services provider"),
("Nic.uk (Nominet resellers)", "https://www.nominet.uk/", "Resellers for .uk via Nominet"),
("Internet.bs", "https://internet.bs/", "Offers on various TLDs"),
("Domain.com", "https://www.domain.com/", "Commercial and marketing-focused"),
("Alibaba Cloud Domains", "https://www.alibabacloud.com/", "Strong in Asia, part of Alibaba Cloud"),
("Hetzner", "https://www.hetzner.com/", "German provider with web services"),
("IONOS by 1&1 (regional)", "https://www.ionos.com/", "Regional variant of IONOS"),
("Names.co.uk", "https://www.names.co.uk/", "Registrar and hosting in the UK"),
("Rebel.com", "https://www.rebel.com/", "Popular in Canada"),
("Crazy Domains", "https://www.crazydomains.com/", "Strong in Asia-Pacific"),
("Netim", "https://www.netim.com/", "European registrar, good TLD support"),
("Key-Systems GmbH", "https://www.key-systems.net/", "Backend and WHOIS services"),
("GMO Registry / Onamae", "https://www.onamae.com/", "Large in Japan"),
("Sedo (marketplace)", "https://sedo.com/", "Marketplace and parking, also domain sales"),
("Flippa", "https://flippa.com/", "Marketplace for domains and sites"),
("DomainFactory", "https://www.df.eu/", "German provider of domains and hosting"),
("ResellerClub", "https://www.resellerclub.com/", "Wholesale and panel for resellers"),
("Names.co", "https://www.names.co/", "Domain and hosting services"),
("HostGator", "https://www.hostgator.com/", "Hosting with registration option"),
("Netregistry", "https://www.netregistry.com.au/", "Popular registrar in Australia"),
("CrazyDomains AU", "https://www.crazydomains.com.au/", "Focus on Australia/Asia"),
("OVH (regional)", "https://www.ovhcloud.com/", "Regional variants of OVH"),
("Scaleway", "https://www.scaleway.com/", "French provider with cloud services"),
("NameBright", "https://www.namebright.com/", "Marketplace and registrar"),
("EuroDNS reseller partners", "https://www.eurodns.com/", "Network of resellers"),
("InternetX", "https://www.internetx.com/", "Registrar and European backend"),
("NicMexico (MX providers)", "https://www.nic.mx/", "Authorized providers for .mx"),
("NIC.br (Brazil providers)", "https://registro.br/", "Providers for .br"),
("AFNIC resellers", "https://www.afnic.fr/", "Resellers for .fr domains"),
("Donweb", "https://donweb.com/", "Popular in Latin America"),
("West263", "https://www.263.net/", "Provider in China"),
("PublicDomainRegistry (PDR)", "https://www.publicdomainregistry.com/", "Domain wholesale provider"),
("NamesDirect", "https://www.namesdirect.com/", "Registrar and reseller"),
("GKG.net", "https://www.gkg.net/", "Domain services for brands"),
("EuroTraffic", "https://eurotraffic.com/", "Marketplace and parking"),
("Dyn (Oracle Dyn)", "https://dyn.com/", "DNS and services, historically domain management"),
("Alibaba Domains (international)", "https://name.alibaba.com/", "Registration and related services"),
("Kavi", "https://www.kavi.com/", "Registrar and reseller"),
("Nic.at (Austrian resellers)", "https://www.nic.at/", "Resellers for .at"),
("NIC.ch (Switzerland resellers)", "https://www.nic.ch/", "Resellers for .ch"),
("MarkMonitor (corporate protection)", "https://www.markmonitor.com/", "Brand protection"),
("CSC Digital Brand Services", "https://www.cscglobal.com/", "Corporate domain portfolio management");
