package operatingsystems

import (
	"database/sql"
	"fmt"
	"html"
	"html/template"
	"io/fs"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	operatingsystem "codeberg.org/urutau-ltd/gavia/internal/models/operating_system"
	"codeberg.org/urutau-ltd/gavia/internal/ui"
)

// defaultLimit and maxLimit keep list endpoints bounded even when query params are missing or invalid.
const (
	defaultLimit int = 10
	maxLimit     int = 100
)

type Handler struct {
	logger *slog.Logger
	tmpl   *template.Template
	osRepo *operatingsystem.OperatingSystemRepository
}

// pageData is the template contract for operating systems screens.
// Keeping view state in one struct makes it explicit which fields frive
// the list/editor partials.
type pageData struct {
	// this data is generated by Gavia. If you need to change this in some
	// way, please refer to indernal/ui/common.go
	ui.BaseData

	OperatingSystems []*operatingsystem.OperatingSystem
	OperatingSystem  *operatingsystem.OperatingSystem // Does it truly need to be a *?
	SearchTerm       string
	// The maximum amount of operatingsystems to show on the operatingsystem-list.html
	// component.
	Limit      int
	EditorMode string
	FormAction string
	FormSubmit string
	NoticeHTML template.HTML
	ErrorHTML  template.HTML
}

func NewHandler(l *slog.Logger, uiFS fs.FS, db *sql.DB) *Handler {
	t := template.Must(template.ParseFS(uiFS,
		"layout/base.html",
		"features/operating_systems/views/*.html",
		"components/*.html",
	))

	return &Handler{
		logger: l,
		tmpl:   t,
		osRepo: operatingsystem.NewOperatingSystemRepository(db),
	}
}

func (h *Handler) Index(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	writeHTMLHeader(w)
	if h.isListRequest(r) {
		h.renderTemplate(w, "os-list", data)
		return
	}

	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)

}

// New serves GET /os/new and prepares the editor in create mode.
// The same endpoint supports full-page rendering and editor-only HTMX swaps.
func (h *Handler) New(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	data.EditorMode = "new"
	data.FormAction = "/os"
	data.FormSubmit = "Create operating system"
	data.OperatingSystem = &operatingsystem.OperatingSystem{}

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Show serves GET /os/{id} and loads the detail panel.
// It keeps list state alive so users can inspect rows without losing current filters.
func (h *Handler) Show(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	p, err := h.osRepo.GetByID(r.Context(), id)
	if err != nil {
		h.logger.Error("Failed to load operating system", "id", id, "err", err)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "Unable to load Operating System")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if p == nil {
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("warn", "Operating system not found.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusNotFound)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	data.EditorMode = "detail"
	data.OperatingSystem = p

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Edit serves GET /os/{id}/edit and pre-fills the form with current values.
// This endpoint is intentionally read-only; persistence happens in Update.
func (h *Handler) Edit(w http.ResponseWriter, r *http.Request) {
	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	p, err := h.osRepo.GetByID(r.Context(), id)
	if err != nil {
		h.logger.Error("Failed to load operating system for edit", "id", id, "err", err)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "Unable to load the operating system to be edited.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if p == nil {
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("warn", "Operating system not found.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusNotFound)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	data.EditorMode = "edit"
	data.OperatingSystem = p
	data.FormAction = fmt.Sprintf("/os/%s/edit", p.Id)
	data.FormSubmit = "Update operating system"

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-panel", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Create handles POST /os and persists a new operating system.
// After successful creation it returns both refreshed editor and list fragments for HTMX.
func (h *Handler) Create(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "invalid form", http.StatusBadRequest)
		return
	}

	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	name := strings.TrimSpace(r.Form.Get("name"))
	notes := strings.TrimSpace(r.Form.Get("notes"))

	data.EditorMode = "new"
	data.FormAction = "/os"
	data.FormSubmit = "Create operating system"
	data.OperatingSystem = &operatingsystem.OperatingSystem{
		Name:  name,
		Notes: optionalString(notes),
	}

	if name == "" {
		data.ErrorHTML = bannerHTML("bad", "Name is required.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if err := h.osRepo.Create(r.Context(), data.OperatingSystem); err != nil {
		h.logger.Error("Failed to create operating system", "err", err)
		status := http.StatusInternalServerError
		msg := "Unable to create operating system."
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			status = http.StatusConflict
			msg = "An operating system with that name already exists."
		}
		data.ErrorHTML = bannerHTML("bad", msg)
		writeHTMLHeader(w)
		w.WriteHeader(status)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	updatedOperatingSystems, listErr := h.osRepo.GetAll(r.Context(), data.SearchTerm, data.Limit)
	if listErr != nil {
		h.logger.Error("Failed to refresh operating system list", "err", listErr)
	} else {
		data.OperatingSystems = updatedOperatingSystems
	}

	data.EditorMode = "detail"
	data.NoticeHTML = bannerHTML("ok", "Operating System created correctly.")

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-response", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Update handles POST /os/{id}/edit and persists operating system changes.
// It validates existence first to distinguish not-found from write failures.
func (h *Handler) Update(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "invalid form", http.StatusBadRequest)
		return
	}

	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	name := strings.TrimSpace(r.Form.Get("name"))
	notes := strings.TrimSpace(r.Form.Get("notes"))

	data.EditorMode = "edit"
	data.FormAction = fmt.Sprintf("/os/%s/edit", id)
	data.FormSubmit = "Update operating system"
	data.OperatingSystem = &operatingsystem.OperatingSystem{
		Id:    id,
		Name:  name,
		Notes: optionalString(notes),
	}

	if name == "" {
		data.ErrorHTML = bannerHTML("bad", "Name is required.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	current, findErr := h.osRepo.GetByID(r.Context(), id)
	if findErr != nil {
		h.logger.Error("Failed to load operating system for update", "id", id, "err", findErr)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "Unable to validate the operating system to update.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if current == nil {
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("warn", "Operating system not found.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusNotFound)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	if err := h.osRepo.Update(r.Context(), data.OperatingSystem); err != nil {
		h.logger.Error("Failed to update operating system", "id", id, "err", err)
		status := http.StatusInternalServerError
		msg := "No se pudo actualizar el operating system."
		if strings.Contains(strings.ToLower(err.Error()), "unique") {
			status = http.StatusConflict
			msg = "An operating system with that name already exists."
		}
		data.ErrorHTML = bannerHTML("bad", msg)
		writeHTMLHeader(w)
		w.WriteHeader(status)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-panel", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	refreshed, getErr := h.osRepo.GetByID(r.Context(), id)
	if getErr != nil {
		h.logger.Error("Failed to reload operating system after update", "id", id, "err", getErr)
	} else if refreshed != nil {
		data.OperatingSystem = refreshed
	}

	updatedOperatingSystems, listErr := h.osRepo.GetAll(r.Context(), data.SearchTerm, data.Limit)
	if listErr != nil {
		h.logger.Error("Failed to refresh operating system list", "err", listErr)
	} else {
		data.OperatingSystems = updatedOperatingSystems
	}

	data.EditorMode = "detail"
	data.NoticeHTML = bannerHTML("ok", "Operating system updated correctly.")

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-response", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// Delete handles DELETE /os/{id}.
// On success it refreshes the list and resets the editor state so UI stays coherent.
func (h *Handler) Delete(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "invalid form", http.StatusBadRequest)
		return
	}

	start := time.Now()
	data, err := h.loadPageData(r, start)
	if err != nil {
		h.logger.Error("Failed to list operating systems", "err", err)
		http.Error(w, "Not found", http.StatusNotFound)
		return
	}

	id := r.PathValue("id")
	if err := h.osRepo.Delete(r.Context(), id); err != nil {
		h.logger.Error("Failed to delete operating system", "id", id, "err", err)
		data.EditorMode = "flash"
		data.ErrorHTML = bannerHTML("bad", "Unable to delete operating system.")
		writeHTMLHeader(w)
		w.WriteHeader(http.StatusBadRequest)
		if h.isEditorRequest(r) {
			h.renderTemplate(w, "os-editor-response", data)
			return
		}
		h.renderTemplate(w, "base", data)
		return
	}

	updatedOperatingSystems, listErr := h.osRepo.GetAll(r.Context(), data.SearchTerm, data.Limit)
	if listErr != nil {
		h.logger.Error("Failed to refresh operating systems list", "err", listErr)
	} else {
		data.OperatingSystems = updatedOperatingSystems
	}

	data.EditorMode = "flash"
	data.NoticeHTML = bannerHTML("ok", "Operating system deleted successfully.")

	writeHTMLHeader(w)
	if h.isEditorRequest(r) {
		h.renderTemplate(w, "os-editor-response", data)
		return
	}

	h.renderTemplate(w, "base", data)
}

// loadPageData gathers list state and records needed by operating system templates.
// Centralizing this avoids duplicating filter+query wiring across handlers.
func (h *Handler) loadPageData(r *http.Request, start time.Time) (pageData, error) {
	searchTerm, limit := parseListState(r)
	OperatingSystems, err := h.osRepo.GetAll(r.Context(), searchTerm, limit)
	if err != nil {
		return pageData{}, err
	}

	return pageData{
		BaseData:         ui.NewBaseData("Operating Systems", start),
		OperatingSystems: OperatingSystems,
		SearchTerm:       searchTerm,
		Limit:            limit,
		EditorMode:       "empty",
		FormAction:       "/os",
		FormSubmit:       "Create operating system",
	}, nil
}

// renderTemplate executes a named template and logs rendering failures.
// Keeping this helper avoids repeating identical error handling in each endpoint.
func (h *Handler) renderTemplate(w http.ResponseWriter, tmpl string, data any) {
	if err := h.tmpl.ExecuteTemplate(w, tmpl, data); err != nil {
		h.logger.Error("Error rendering template", "template", tmpl, "err", err)
	}
}

// isListRequest detects HTMX calls that target only the operatingsystems table body.
// This allows one route to serve both full and partial responses safely.
func (h *Handler) isListRequest(r *http.Request) bool {
	if r.Header.Get("HX-Request") != "true" || r.Header.Get("HX-Boosted") == "true" {
		return false
	}

	target := strings.TrimSpace(r.Header.Get("HX-Target"))
	if target == "os-body" || target == "#os-body" {
		return true
	}

	trigger := strings.TrimSpace(r.Header.Get("HX-Trigger"))
	triggerName := strings.TrimSpace(r.Header.Get("HX-Trigger-Name"))

	return trigger == "os-limit" ||
		trigger == "os-search" ||
		triggerName == "limit" ||
		triggerName == "q"
}

// isEditorRequest detects HTMX calls that target the right-side operatingsystem editor panel.
func (h *Handler) isEditorRequest(r *http.Request) bool {
	if r.Header.Get("HX-Request") != "true" || r.Header.Get("HX-Boosted") == "true" {
		return false
	}

	target := strings.TrimSpace(r.Header.Get("HX-Target"))
	return target == "os-editor" || target == "#os-editor"
}

func optionalString(value string) *string {
	if value == "" {
		return nil
	}

	return new(value)
}

// parseListState reads query/form list controls shared by full requests and HTMX swaps.
func parseListState(r *http.Request) (string, int) {
	_ = r.ParseForm()
	searchTerm := strings.TrimSpace(r.Form.Get("q"))
	limit := parseLimit(r.Form.Get("limit"))
	return searchTerm, limit
}

// parseLimit normalizes user-provided limits into a safe range.
func parseLimit(raw string) int {
	if raw == "" {
		return defaultLimit
	}

	limit, err := strconv.Atoi(raw)
	if err != nil || limit <= 0 {
		return defaultLimit
	}

	if limit > maxLimit {
		return maxLimit
	}

	return limit
}

// bannerHTML builds a sanitized alert block compatible with Missing.css semantic classes.
func bannerHTML(kind, msg string) template.HTML {
	className := "info"
	switch kind {
	case "ok", "bad", "warn", "info":
		className = kind
	}

	escaped := html.EscapeString(msg)
	return template.HTML(`<p class="os-alert ` + className + `">` + escaped + `</p>`)
}

// writeHTMLHeader enforces a consistent HTML content type for template responses.
func writeHTMLHeader(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
}
